version: "3.8"
services:
  db:
    container_name: chat-db
    image: postgres
    restart: always
    ports:
      - 5421:5421
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgresql/data

  adminer:
    container_name: chat-admin
    image: adminer
    restart: always
    ports:
      - 8080:8080
