version: "3.8"
services:
  db:
    container_name: chat_db
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/db:/var/lib/postgres/data/postgresql/data

  adminer:
    container_name: chat_admin
    image: adminer
    restart: always
    ports:
      - 8080:8080
